Use escuela;
DROP TABLE inscripciones;
DROP TABLE comisiones;
DROP TABLE asistencias;
DROP TABLE profesores;
DROP TABLE cedes;
DROP TABLE cursos;
DROP TABLE dificultad;
DROP TABLE categorias;
DROP TABLE alumnos;
DROP TABLE notas;
